### ISSUE TITLE
Compile errors on apple clang

### ISSUE THREAD

**Issue by sbusch42** [cginternals/cppassist#19]
The following compile errors occur inside the simd code on Apple LLVM version 8.0.0 (clang-800.0.42.1):

cppassist/source/cppassist/include/cppassist/simd/vector.inl:169:12: error
  cannot initialize return object of type 'float *' with an rvalue of type 'const float *'
    return data() + size();

static_assert failed "Allocator::value_type must be same type as value_type"
  [...]
  vector.h:28:36

**Comment by scheibel** [comment]
I just had a look at both code fragments.
For both errors I doesn't see any flaw in the source code; especially I don't understand the error message of the Allocator::value_type and their context.
The first error may be a misinterpretation of AppleClang regarding overloaded member functions for both const and non-const objects or a more restrictive pointer arithmetic.

I'll test on a macOS.

**Comment by sbusch42** [comment]
Regarding the second error:
    using value_type = value<T, SIMD_SIZE>;
    using allocator = cppassist::aligned_allocator<T, simd_size * sizeof(T)>;
    using iterator = typename std::vector<value_type, allocator>::iterator;

The value type for the vector is value_type (which is value<T, SIMD_SIZE>).
The value type for the allocator is T.

T != value<T, SIMD_SIZE), hence the error message. It can be solved syntactically by
    using allocator = cppassist::aligned_allocator<value_type, simd_size * sizeof(T)>;

however I'm not sure if this is correct semantically. Should at least read sizeof(value_type), I guess?

**Comment by sbusch42** [comment]
I don't understand the first error at all. The function that is called in non-const, so the used version of data() should also be the non-const version. But it seems like the compiler chooses the const version of data() here. I don't know what to do here except circumventing this possible compiler bug by using a const_cast.

**Comment by scheibel** [comment]
I just want to add that clang 3.8 (the official clang, not apple clang) has no problem with the constness.

I will provide a const_cast solution.

**Comment by scheibel** [comment]
Somehow, the first error vanished while fixing the second one on apple clang 8.0.

**Comment by sbusch42** [comment]
true, it's gone. So with luck this was just a very strange follow-up bug.
