### ISSUE TITLE
File system watcher

### ISSUE THREAD

**Issue by sbusch42** [cginternals/cppassist#4]
Implement a cross-platform file watcher that works at least on Linux, Windows, and MacOS. It should be able to watch single files, and, if possible, directories and emit a callback when a file has changed.

**Comment by scheibel** [comment]
I doubt that this is even possible, but I would like to have a watcher that also recognizes new files, deletion, rename/move and can handle the _replace instead of update for save_ problem.

**Comment by sbusch42** [comment]
Let's have a look at https://github.com/mgerhardy/simplefilewatcher

**Comment by sbusch42** [comment]
moving this to cppfs
