### ISSUE TITLE
Flag operators intefere with other libraries

### ISSUE THREAD

**Issue by j-o** [cginternals/cppassist#53]
This overload may get picked for just about any enum type if `cppassist/Flags.h` is included in a compilation unit, even when it is not intended:
```
template <typename EnumType>
auto operator|(EnumType flag1, EnumType flag2) -> typename std::enable_if<std::is_enum<EnumType>::value, cppassist::Flags<EnumType>>::type;
```
One such instance would be this line from `sstream` of the recent Visual Studio 15.8 update:
```
constexpr auto _Both = ios_base::in | ios_base::out;
```
Which fails to compile because `cppassist::Flags` is not `constexpr`. **Cppassist should in no way be involved in this line buried deeply in the stdlib implementation.**

Therefore I strongly suggest to remove this overload and the corresponding ones for `operator&` and `operator^`.

**Comment by scheibel** [comment]
We're working on it.

**Comment by scheibel** [comment]
Current approach: remove general enum overload, we expect an explicit cast to at least one of the parameters to the `cppassist::Flags` type in order to allow flag operations.
