### ISSUE TITLE
Integrate ConvertUTF

### ISSUE THREAD

**Issue by scheibel** [cginternals/cppassist#61]
Similar to the integration in cppexpose:
* [x] add `3rdparty` directory to the root and register ConvertUTF as separate cmake target (https://github.com/cginternals/cppexpose/tree/2.0/3rdparty/linenoise-ng).
* [x] Use ConvertUTF to handle UTF conversions within `cppassist/string/conversion`.
* [x] Add license of ConvertUTF to own license.

**Comment by cgcostume** [comment]
seems to be done.
